//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forecast.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\DB\\Indicators.sdf")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://analytics-service.client.getshopster.net/report_api/query_report/dev/outdoor_ad_spaces_ots_distibution_hours_of_day_weekdays/?input_parameters={""access_token"": ""911b55e6-5d44-4e71-8566-d3ed41dd1aa4"",""outdoor_ad_space_ids"":[132430],""main_date_range"":[""startDate"",""endDate""],""region_id"": 4}")]
        public string OTS_days {
            get {
                return ((string)(this["OTS_days"]));
            }
            set {
                this["OTS_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://analytics-service.client.getshopster.net/report_api/query_report/dev/outdoor_ad_spaces_ots_distibution_hours_of_day_weekends/?input_parameters={""access_token"": ""911b55e6-5d44-4e71-8566-d3ed41dd1aa4"",""outdoor_ad_space_ids"":[132430],""main_date_range"":[""startDate"",""endDate""],""region_id"": 4}")]
        public string OTS_holi {
            get {
                return ((string)(this["OTS_holi"]));
            }
            set {
                this["OTS_holi"] = value;
            }
        }
    }
}
